Import ('env')
 
name = 'nucapp'
inc = env.Dir('.')
src = env.Glob('*.cpp')

CXXFLAGS = ['-Wno-long-long']
deps = ['nuca', 'QtCore', 'QtGui']

if env['QT_PRESENT']:
    env.Uic4(Glob('*.ui'))

env.Append(CXXFLAGS=CXXFLAGS, CFLAGS=CXXFLAGS)
env.CreateProgram(name, inc, src, deps)

